### PR TITLE
updating to use secrets

### PR DESCRIPTION
**Pull request by coreydaley**
@bparees ptal

### CODE REVIEW

**Comment by bparees** [comment]
lgtm.

**Comment by bparees** [comment]
wait you missed updating the DB DC.

**Comment by coreydaley** [comment]
@bparees this one should be fixed now

**Comment by bparees** [comment]
you missed the dbadminpassword in the DB dc.

**Comment by coreydaley** [comment]
@bparees this one should be good now

**Comment by bparees** [comment]
lgtm

**Pull request merged**
