### PR TITLE
Parameterize service and routes consistently

### PR DESCRIPTION
**Pull request by sspeiche**
I went with a minimal set of parameters (service name and route) and derived other names (to avoid conflict) based on the service name.

I'm not 100% sure that line 231 should use the name of the template or the name of the service parameter.  Perhaps I need to add a 2nd parameter.

@bparees If you could review to make sure this is what instantapp templates should look like when being created multiple times in same project

### CODE REVIEW

**Comment by bparees** [comment]
i don't know that we need to enable users to instantiate a template multiple times in a single project.

**Comment by sspeiche** [comment]
Think I misunderstood your feedback on the parameterization of the service name.  What all do you think should be parameterized then?

**Comment by bparees** [comment]
just the service name and the corresponding link in the route definition i believe.

**Comment by bparees** [comment]
these changes look fine but unfortunately it needs a rebase now.

**Comment by bparees** [comment]
lgtm, thanks @sspeiche!

**Pull request merged**
