### PR TITLE
add unit tests for post commit hook

### PR DESCRIPTION
**Pull request by PI-Victor**
fixes https://github.com/openshift/nodejs-ex/issues/32
fixes https://github.com/openshift/nodejs-ex/issues/18

@bparees @rhcarvalho PTAL.
tested by building it in origin 

_works on my machine_ .

### CODE REVIEW

**Comment by bparees** [comment]
nice work!  lgtm, squash?

**Comment by PI-Victor** [comment]
squashed as requested

**Comment by bparees** [comment]
lgtm

**Comment by PI-Victor** [comment]
@bparees awesome, thanks!

**Pull request merged**
