### PR TITLE
use an emptydir volume for mongodb instead of no volume

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@markturansky @luciddreamz ptal

**Comment by luciddreamz** [comment]
Looks good

**Comment by markturansky** [comment]
Template works great.

```
★ markturansky:~/Projects/src/github.com/markturansky/nodejs  
$ oc new-app -f openshift/templates/nodejs-mongodb.json -e SOURCE_REPOSITORY_URL=https://github.com/markturansky/nodejs-ex
--> Deploying template nodejs-mongodb-example for "openshift/templates/nodejs-mongodb.json"
     With parameters:
      Name=nodejs-mongodb-example
      Namespace=openshift
      Memory Limit=512Mi
      Memory Limit (MongoDB)=512Mi
      Git Repository URL=https://github.com/openshift/nodejs-ex.git
      Git Reference=
      Context Directory=
      Application Hostname=
      GitHub Webhook Secret=xqeVHAbfPvQbNENGl1sq32i1MhegS3TaNSmxiUMT # generated
      Generic Webhook Secret=GNCmmVvVkkelDi4JwRCvRUXtMBJkvmcIaIeN73Iu # generated
      Database Service Name=mongodb
      MongoDB Username=userV82 # generated
      MongoDB Password=RqVUHO8pnaGFN1IL # generated
      Database Name=sampledb
      Database Administrator Password=ScFAkVGuwPsyxEVv # generated
--> Creating resources with label app=nodejs-mongodb-example ...
    service "nodejs-mongodb-example" created
    route "nodejs-mongodb-example" created
    imagestream "nodejs-mongodb-example" created
    buildconfig "nodejs-mongodb-example" created
    deploymentconfig "nodejs-mongodb-example" created
    service "mongodb" created
    deploymentconfig "mongodb" created
--> Success
    Build scheduled, use 'oc logs -f bc/nodejs-mongodb-example' to track its progress.
    Run 'oc status' to view your app.

★ markturansky:~/Projects/src/github.com/markturansky/nodejs  
$ oc get dc
NAME                     REVISION   REPLICAS   TRIGGERED BY
mongodb                  1          1          config
nodejs-mongodb-example   0          1          config,image(nodejs-mongodb-example:latest)

★ markturansky:~/Projects/src/github.com/markturansky/nodejs  
$ oc get pod
NAME                             READY     STATUS    RESTARTS   AGE
mongodb-1-vcdm2                  1/1       Running   0          31s
nodejs-mongodb-example-1-build   1/1       Running   0          38s
```

and in `oc describe dc mongodb`

```
Volumes:
   mongodb-data:
    Type:	EmptyDir (a temporary directory that shares a pod's lifetime)
```

**Comment by bparees** [comment]
thanks @markturansky

**Pull request merged**
