### PR TITLE
execute tests against remote instance

### PR DESCRIPTION
**Pull request by PI-Victor**
@tnozicka can you please git clone this and give it a try?
what you need is to export a variable HTTP_TEST_SERVER with your http://remoteinstance:port and the tests will be executed against that instance. Hope this helps, let me know.

@bparees PTAL.

done according to https://github.com/chaijs/chai-http#url

also i've tested this locally and it works.

fixes https://github.com/openshift/nodejs-ex/issues/59

### CODE REVIEW

**Comment by bparees** [comment]
lgtm

**Comment by tnozicka** [comment]
@PI-Victor Sorry, it took me some time to get to it. You guys were too quick :)

Thanks, it is working fine for me!

There is only one little thing. It runs its own server even when connecting to remote one. This is a bit confusing and on first look, it lets you question if it's really run against remove server.

```
+ HTTP_TEST_SERVER=http://nodejs-ex-dev:8080
+ ./node_modules/mocha/bin/mocha --timeout 5000 tests/app_test.js --reporter xunit
+ tee report.xml
```
```
Server running on http://0.0.0.0:8080
```
```
<testsuite name="Mocha Tests" tests="2" failures="0" errors="0" skipped="0" timestamp="Mon, 01 Aug 2016 18:43:36 GMT" time="0.05">
<testcase classname="Basic routes tests" name="GET to / should return 200" time="0.03"/>
<testcase classname="Basic routes tests" name="GET to /pagecount should return 200" time="0.009"/>
</testsuite>
```

**Comment by PI-Victor** [comment]
@tnozicka well, the test that i did was rather simple. you can do 

```
Victors-MacBook-Air:nodejs-ex ipalade$ PORT=1030 npm start

> nodejs-ex@0.0.1 start /Users/ipalade/projects/nodejs-ex
> node server.js

Server running on http://0.0.0.0:1030
127.0.0.1 - - [01/Aug/2016:21:20:16 +0000] "GET / HTTP/1.1" 200 40382 "-" "node-superagent/1.2.0"
127.0.0.1 - - [01/Aug/2016:21:20:16 +0000] "GET /pagecount HTTP/1.1" 200 17 "-" "node-superagent/1.2.0"
```

```
Victors-MacBook-Air:nodejs-ex ipalade$ HTTP_TEST_SERVER=http://localhost:1030 npm test

> nodejs-ex@0.0.1 test /Users/ipalade/projects/nodejs-ex
> IP=0.0.0.0 PORT=3030 mocha --timeout 5000 tests/*_test.js

Server running on http://0.0.0.0:3030


  Basic routes tests
    ✓ GET to / should return 200 (48ms)
    ✓ GET to /pagecount should return 200


  2 passing (71ms)
```
--- tests are passing, once you kill this instance


```
Victors-MacBook-Air:nodejs-ex ipalade$ HTTP_TEST_SERVER=http://localhost:1030 npm test

> nodejs-ex@0.0.1 test /Users/ipalade/projects/nodejs-ex
> IP=0.0.0.0 PORT=3030 mocha --timeout 5000 tests/*_test.js

Server running on http://0.0.0.0:3030


  Basic routes tests
    1) GET to / should return 200
double callback!
    2) GET to /pagecount should return 200
double callback!


  0 passing (34ms)
  2 failing

  1) Basic routes tests GET to / should return 200:
     Uncaught TypeError: Cannot read property 'should' of undefined
      at tests/app_test.js:16:16
      at Test.Request.callback (node_modules/superagent/lib/node/index.js:781:12)
      at ClientRequest.<anonymous> (node_modules/superagent/lib/node/index.js:736:10)
      at Socket.socketErrorListener (_http_client.js:308:9)
      at emitErrorNT (net.js:1271:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

  2) Basic routes tests GET to /pagecount should return 200:
     Uncaught TypeError: Cannot read property 'should' of undefined
      at tests/app_test.js:26:16
      at Test.Request.callback (node_modules/superagent/lib/node/index.js:781:12)
      at ClientRequest.<anonymous> (node_modules/superagent/lib/node/index.js:736:10)
      at Socket.socketErrorListener (_http_client.js:308:9)
      at emitErrorNT (net.js:1271:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)
npm ERR! Test failed.  See above for more details.
```
i'm quite sure they run against the remote instance.

**Comment by PI-Victor** [comment]
oh, it probably evaluates the `server` *object* hence the log `Server running on http://0.0.0.0:3030` you can ignore that.

**Comment by tnozicka** [comment]
@PI-Victor Yeah, I am sure they run against the remote instance, too, but I had to try it to find out. The *"Server running on"* message is a bit misleading, so I wanted you to know about it. It is because of evaluating the server object as you say.

But I am happy with the state as is. Good job and thank you for sending this PR.

**Pull request merged**
